GET http://localhost:8000/api/helloworld/
Accept: application/json

###

GET http://localhost:8000/api/note/
Accept: application/json

###

GET http://localhost:8000/api/note/?date_from=2022/03/13 19:51:00
Accept: application/json

###

GET http://localhost:8000/api/note/?date_from=2022/03/13 19:51:00&title=3
Accept: application/json

###

GET http://localhost:8000/api/note/?date_from=2022/03/13 19:51:30
Accept: application/json

###

GET http://localhost:8000/api/note/?rank=7
Accept: application/json

###

GET http://localhost:8000/api/note/?date_from=202203/13 19:51:30
Accept: application/json

###

GET http://localhost:8000/api/note/?rank=asdf
Accept: application/json

###


GET http://localhost:8000/api/note/?date_from=202203/13 19:51:30&rank=12345678901234567890as
Accept: application/json

###

POST http://localhost:8000/api/note/
Content-Type: application/json

{
    "title": "title3",
    "content": "contetewtsentsentse003"
}

###
